package com.google.cloud.genomics.denovo;

import com.google.cloud.genomics.denovo.DenovoUtil.Genotype;

import java.util.List;

/**
 * TODO: Insert description here. (generated by smoitra)
 */
public class BayesInferenceResult {
  private final List<Genotype> maxTrioGenotype;
  private final double maxLikelihood;
  private final double bayesDenovoProb;
  private final double likelihoodRatio;
  private final double mendelianLogLikelihood;
  private final double denovoLogLikelihood;

  public BayesInferenceResult(List<Genotype> maxTrioGenotype,
      double maxLikelihood,
      double bayesDenovoProb,
      double logOfLikelihoodRatio,
      double mendelianLogLikelihood,
      double denovoLogLikelihood) {
    this.maxTrioGenotype = maxTrioGenotype;
    this.maxLikelihood = maxLikelihood;
    this.bayesDenovoProb = bayesDenovoProb;
    this.likelihoodRatio = logOfLikelihoodRatio;
    this.mendelianLogLikelihood = mendelianLogLikelihood;
    this.denovoLogLikelihood = denovoLogLikelihood;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("<");
    sb.append("maxGT : " + getMaxTrioGenotype().toString());
    sb.append(", maxLL : " + String.valueOf(getMaxLikelihood()));
    sb.append(", mendelLL : " + String.valueOf(getMendelianLogLikelihood()));
    sb.append(", denovoLL : " + String.valueOf(getDenovoLogLikelihood()));
    sb.append(", bayesProb : " + String.valueOf(getBayesDenovoProb()));
    sb.append(", llRatio : " + String.valueOf(getLikelihoodRatio()));
    sb.append(">");
    return sb.toString();
  }

  /**
   * @return the maxTrioGenotype
   */
  public List<Genotype> getMaxTrioGenotype() {
    return maxTrioGenotype;
  }

  /**
   * @return the maxLikelihood
   */
  public double getMaxLikelihood() {
    return maxLikelihood;
  }

  /**
   * @return the bayesDenovoProb
   */
  public double getBayesDenovoProb() {
    return bayesDenovoProb;
  }

  /**
   * @return the likelihoodRatio
   */
  public double getLikelihoodRatio() {
    return likelihoodRatio;
  }

  /**
   * @return the mendelianLogLikelihood
   */
  public double getMendelianLogLikelihood() {
    return mendelianLogLikelihood;
  }

  /**
   * @return the denovoLogLikelihood
   */
  public double getDenovoLogLikelihood() {
    return denovoLogLikelihood;
  }
}
