package com.google.cloud.genomics.denovo;



/**
 * TODO: Insert description here. (generated by smoitra)
 */
public class DenovoCallers {

  
  private DenovoCallers() {
    throw new AssertionError("Tried to instantiate non-instantiable class");
  }
  /**
   * @param shared
   * @return Caller that uses variants API
   */
  public static DenovoCaller getVariantCaller(DenovoShared shared) {
    // TODO(smoitra): Auto-generated method stub
    return new VariantCaller(shared);
  }

  /**
   * @param shared
   * @return Calle that uses reads API
   */
  public static DenovoCaller getReadCaller(DenovoShared shared) {
    // TODO(smoitra): Auto-generated method stub
    return new ReadCaller(shared);
  }
}
