/*
 *Copyright 2014 Google Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.cloud.genomics.denovo;



/**
 * TODO: Insert description here. (generated by smoitra)
 */
public class DenovoCallers {

  
  private DenovoCallers() {
    throw new AssertionError("Tried to instantiate non-instantiable class");
  }
  /**
   * @param shared
   * @return Caller that uses variants API
   */
  public static DenovoCaller getVariantCaller(DenovoShared shared) {
    // TODO(smoitra): Auto-generated method stub
    return new VariantCaller(shared);
  }

  /**
   * @param shared
   * @return Calle that uses reads API
   */
  public static DenovoCaller getReadCaller(DenovoShared shared) {
    // TODO(smoitra): Auto-generated method stub
    return new ReadCaller(shared);
  }
}
