package com.google.cloud.genomics.denovo;

import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;

/**
 * TODO: Insert description here. (generated by smoitra)
 */
public abstract class DenovoCaller {

  public abstract void execute() throws ParseException, IOException;
  
  
  CallHolder parseLine(String line) throws ParseException {
    String[] splitLine = line.split(",");
    if (splitLine.length < 2) {
      throw new ParseException("Could not parse line : " + line, 0);
    }
    String chromosome = splitLine[0];
    Long candidatePosition = Long.valueOf(splitLine[1]);
    CallHolder callHolder = new CallHolder(chromosome, candidatePosition);
    return callHolder;
  }

  /*
   * Writes calls to print stream
   */
  synchronized void writeCalls(PrintWriter writer, String calls) {
    writer.print(calls);
    writer.flush();
  }

  class CallHolder {
    final String chromosome;
    final Long position;

    CallHolder(String chromosome, Long position) {
      this.chromosome = chromosome;
      this.position = position;
    }

    @Override
    public String toString() {
      return String.format("<%s,%s>", chromosome, position);
    }
  }
  
  
}
