/*
 *Copyright 2014 Google Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.cloud.genomics.denovo;

import static org.junit.Assert.*;

import com.google.cloud.genomics.denovo.DenovoUtil.Genotypes;
import com.google.cloud.genomics.denovo.DenovoUtil.TrioIndividual;

import static com.google.cloud.genomics.denovo.DenovoUtil.Genotypes.*;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * TODO: Insert description here. (generated by smoitra)
 */
public class DenovoBayesNetTest {

  /**
   * Test method for
   * {@link com.google.cloud.genomics.denovo.DenovoBayesNet#DenovoBayesNet(double, double)}.
   */

  private DenovoBayesNet dbn;
  private Map<List<Genotypes>, Double> conditionalProbabilityTable;
  private double EPS = 1e-12;

  @Before
  public void setUp() {
    dbn = new DenovoBayesNet(1e-2, 1e-8);

    conditionalProbabilityTable = new HashMap<>();
    int numGenotypes = Genotypes.values().length;
    for (Genotypes genotype : Genotypes.values()) {
      conditionalProbabilityTable.put(Collections.singletonList(genotype),
          Double.valueOf(1.0 / numGenotypes));
    }

    // makes sure conditionalProbabilityTable is set up properly
    double totProb = 0.0;
    for (Double prob : conditionalProbabilityTable.values()) {
      totProb += prob;
    }
    assertTrue((totProb >= 1 - EPS && totProb <= 1 + EPS));
  }

  @After
  public void tearDown() {
    dbn = new DenovoBayesNet(1e-2, 1e-8);
  }

  @Test
  public void testDenovoBayesNet() {
    assertNotNull(dbn);
    assertTrue(
        dbn.getSequenceErrorRate() >= 1e-2 - 1e-12 && dbn.getSequenceErrorRate() <= 1e-2 + 1e-12);
    assertTrue(
        dbn.getDenovoMutationRate() >= 1e-8 - 1e-12 && dbn.getDenovoMutationRate() <= 1e-8 + 1e-12);
  }

  /**
   * Test method for {@link com.google.cloud.genomics.denovo.DenovoBayesNet#addNode(com.google.cloud.genomics.denovo.Node)}
   */
  @Test
  public void testAddNodeNodeOfTrioIndividualGenotypes() {
    Node<TrioIndividual, Genotypes> dadNode =
        new Node<>(TrioIndividual.DAD, null, conditionalProbabilityTable);

    Node<TrioIndividual, Genotypes> momNode =
        new Node<>(TrioIndividual.MOM, null, conditionalProbabilityTable);

    Node<TrioIndividual, Genotypes> childNode = new Node<>(TrioIndividual.CHILD,
        Arrays.asList(dadNode, momNode), conditionalProbabilityTable);

    dbn.addNode(dadNode);
    dbn.addNode(momNode);
    dbn.addNode(childNode);

    assertEquals(dbn.nodeMap.get(TrioIndividual.DAD), dadNode);
    assertEquals(dbn.nodeMap.get(TrioIndividual.MOM), momNode);
    assertEquals(dbn.nodeMap.get(TrioIndividual.CHILD), childNode);

    assertEquals(dbn.nodeMap.get(TrioIndividual.CHILD).parents, Arrays.asList(dadNode, momNode));
    assertEquals(dbn.nodeMap.get(TrioIndividual.DAD).parents, null);
    assertEquals(dbn.nodeMap.get(TrioIndividual.MOM).parents, null);
  }

  /**
   * Test method for {@link com.google.cloud.genomics.denovo.DenovoBayesNet#createConditionalProbabilityTable(com.google.cloud.genomics.denovo.DenovoUtil.TrioIndividual)}
   * .
   */
  @Test
  public void testDadCreateConditionalProbabilityTable() {
    Map<List<Genotypes>, Double> cpt = dbn.createConditionalProbabilityTable(TrioIndividual.DAD);
    int numGenotypes = Genotypes.values().length;

    // check keys
    assertTrue(
        cpt.keySet().equals(new HashSet<>(Arrays.asList(Collections.singletonList(Genotypes.AA),
            Collections.singletonList(Genotypes.AC),
            Collections.singletonList(Genotypes.AT),
            Collections.singletonList(Genotypes.AG),
            Collections.singletonList(Genotypes.CC),
            Collections.singletonList(Genotypes.CT),
            Collections.singletonList(Genotypes.CG),
            Collections.singletonList(Genotypes.TT),
            Collections.singletonList(Genotypes.TG),
            Collections.singletonList(Genotypes.GG)))));

    // check values
    double probValue = 1.0 / numGenotypes;
    for (Double value : cpt.values()) {
      assertTrue(value >= probValue - EPS && value <= probValue + EPS);
    }

    // check total probability Values
    double totProb = 0.0;
    for (Double value : cpt.values()) {
      totProb += value;
    }
    assertTrue(totProb >= 1.0 - EPS && totProb <= 1.0 + EPS);
  }

  public void testMomCreateConditionalProbabilityTable() {
    Map<List<Genotypes>, Double> cpt = dbn.createConditionalProbabilityTable(TrioIndividual.MOM);
    int numGenotypes = Genotypes.values().length;

    // check keys
    assertTrue(
        cpt.keySet().equals(new HashSet<>(Arrays.asList(Collections.singletonList(Genotypes.AA),
            Collections.singletonList(Genotypes.AC),
            Collections.singletonList(Genotypes.AT),
            Collections.singletonList(Genotypes.AG),
            Collections.singletonList(Genotypes.CC),
            Collections.singletonList(Genotypes.CT),
            Collections.singletonList(Genotypes.CG),
            Collections.singletonList(Genotypes.TT),
            Collections.singletonList(Genotypes.TG),
            Collections.singletonList(Genotypes.GG)))));

    // check values
    double probValue = 1.0 / numGenotypes;
    for (Double value : cpt.values()) {
      assertTrue(value >= probValue - EPS && value <= probValue + EPS);
    }

    // check total probability Values
    double totProb = 0.0;
    for (Double value : cpt.values()) {
      totProb += value;
    }
    assertTrue(totProb >= 1.0 - EPS && totProb <= 1.0 + EPS);
  }

  @Test
  public void testChildCreateConditionalProbabilityTableKeySet() {
    Map<List<Genotypes>, Double> cpt = dbn.createConditionalProbabilityTable(TrioIndividual.CHILD);

    // check keys
    Set<List<Genotypes>> expectedKeySet = new HashSet<>();
    for (Genotypes dadgt : Genotypes.values()) {
      for (Genotypes momgt : Genotypes.values()) {
        for (Genotypes childgt : Genotypes.values()) {
          expectedKeySet.add(Arrays.asList(dadgt, momgt, childgt));
        }
      }
    }
    assertEquals(expectedKeySet, cpt.keySet());
  }

  @Test
  public void testChildCreateConditionalProbabilityTableValues() {
    Map<List<Genotypes>, Double> cpt = dbn.createConditionalProbabilityTable(TrioIndividual.CHILD);

    // check some key values
    assertEquals("TT|AA,AA", 1e-8, cpt.get(Arrays.asList(AA, AA, TT)), 1e-12);
    assertEquals("AT|AA,AA", 1e-8, cpt.get(Arrays.asList(AA, AA, AT)), 1e-12);
    assertEquals("TT|AA,AC", 1e-8, cpt.get(Arrays.asList(AA, AC, TT)), 1e-12);
    assertEquals("CC|AA,AC", 1e-8, cpt.get(Arrays.asList(AA, AC, CC)), 1e-12);
    assertEquals("AT|AA,AC", 1e-8, cpt.get(Arrays.asList(AA, AC, AT)), 1e-12);
    assertEquals("AA|AA,AC", 0.5, cpt.get(Arrays.asList(AA, AC, AA)), 1e-7);
    assertEquals("AC|AA,AC", 0.5, cpt.get(Arrays.asList(AA, AC, AC)), 1e-7);
    assertEquals("GG|AC,TG", 1e-8, cpt.get(Arrays.asList(AC, TG, GG)), 1e-12);
    assertEquals("AA|AC,TG", 1e-8, cpt.get(Arrays.asList(AC, TG, AA)), 1e-12);
    assertEquals("AC|AC,TG", 1e-8, cpt.get(Arrays.asList(AC, TG, AC)), 1e-12);
    assertEquals("TG|AC,TG", 1e-8, cpt.get(Arrays.asList(AC, TG, TG)), 1e-12);
    assertEquals("AT|AC,TG", 0.25, cpt.get(Arrays.asList(AC, TG, AT)), 1e-7);
    assertEquals("CT|AC,TG", 0.25, cpt.get(Arrays.asList(AC, TG, CT)), 1e-7);
    assertEquals("AG|AC,TG", 0.25, cpt.get(Arrays.asList(AC, TG, AG)), 1e-7);
    assertEquals("CG|AC,TG", 0.25, cpt.get(Arrays.asList(AC, TG, CG)), 1e-7);
  }

  @Test
  @Ignore("Known Failure")
  public void testChildCreateConditionalProbabilityTableValuesHarderCases() {
    Map<List<Genotypes>, Double> cpt = dbn.createConditionalProbabilityTable(TrioIndividual.CHILD);

    assertEquals("AA|AC,AC", 0.25, cpt.get(Arrays.asList(AC, AC, AA)), 1e-7);
    assertEquals("AC|AC,AC", 0.5, cpt.get(Arrays.asList(AC, AC, AC)), 1e-7);
    assertEquals("CC|AC,AC", 0.25, cpt.get(Arrays.asList(AC, AC, CC)), 1e-7);

    DenovoBayesNet.printConditionalProbabilityTable(cpt);
  }


  @Test
  public void testChildCreateConditionalProbabilityTableTotalProbability() {
    Map<List<Genotypes>, Double> cpt = dbn.createConditionalProbabilityTable(TrioIndividual.CHILD);

    // Sanity check - probabilities should add up to 1.0 (almost)
    for (Genotypes genoTypeDad : Genotypes.values()) {
      for (Genotypes genoTypeMom : Genotypes.values()) {
        double totProb = 0.0;
        for (Genotypes genoTypeChild : Genotypes.values()) {
          totProb += cpt.get(Arrays.asList(genoTypeDad, genoTypeMom, genoTypeChild));
        }
        assertTrue(totProb >= 1.0 - EPS && totProb <= 1.0 + EPS);
      }
    }
  }



}
